


export const PRODUCTS = [
 
  {
    id: 2,
    ProductName: "Macbook Pro 2022 (M1)",
    Price: 1999.0,
    ProductImage: product2,
    BrandName: 'positive beverage',  
    OldPrice: 39.85,
    value: 'Technology',
    category:"Technology",
    subcategory: 'Iphone',
    img1: M2,
    img2: product2,
    img3: product3,
    img4: M2  
  },
  {
    id: 3,
    ProductName: "Cannon M50 Camera",
    Price: 699.0,
    ProductImage: product3,
    BrandName: 'positive beverage',  
    OldPrice: 39.85,
    value: 'Grocery',
    category:"Technology",
    subcategory: 'Computer',
    img1: M2,
    img2: product2,
    img3: product3,
    img4: M2  
  },
  {
    id: 4,
    ProductName: 'Redmi Note 12 ', 
    Price: 999.0,
    OldPrice: 1050.85,
    ProductImage: M2,
    BrandName: 'Xiaomi',  
    value: 'Technology',
    category:"Technology",
    subcategory: 'Laptop',
    img1: product3,
    img2: product2,
    img3: product3,
    img4: M2 
  },
  {
    id: 5,
    ProductName: 'Computer ', 
    Price: 999.0,
    OldPrice: 1050.85,
    ProductImage: M2,
    BrandName: 'Xiaomi',  
    value: 'Fashion',
    category:"Technology",
    subcategory: 'Accessory',
    img1: product3,
    img2: product2,
    img3: product3,
    img4: M2 
  },
  {
    id: 6,
    ProductName: 'Laptop ', 
    Price: 999.0,
    OldPrice: 1050.85,
    ProductImage: M2,
    BrandName: 'Xiaomi',  
    value: 'F',
    category:"Fashion",
    subcategory: 'Shoe',
    img1: product3,
    img2: product2,
    img3: product3,
    img4: M2 
  },
  {
    id: 7,
    ProductName: 'Fashion1', 
    Price: 999.0,
    OldPrice: 1050.85,
    ProductImage: product3,
    BrandName: 'Xiaomi',  
    value: 'L',
    category:"Fashion",
    subcategory: 'Pant',
    img1: product3,
    img2: product2,
    img3: product3,
    img4: M2 
  },
  {
    id: 8,
    ProductName: 'Fashion2', 
    Price: 999.0,
    OldPrice: 1050.85,
    ProductImage: product2,
    BrandName: 'Xiaomi',  
    value: 'P',
    category:"Fashion",
    subcategory: 'Kid',
    img1: product3,
    img2: product2,
    img3: product3,
    img4: M2 
  },
  {
    id: 9,
    ProductName: 'Fashion3', 
    Price: 999.0,
    OldPrice: 1050.85,
    ProductImage: M2,
    BrandName: 'Xiaomi',  
    value: 'P',
    category:"Fashion",
    subcategory: 'Beauty',
    img1: product3,
    img2: product2,
    img3: product3,
    img4: M2 
  },
  {
    id: 10,
    ProductName: 'Fashion4', 
    Price: 999.0,
    OldPrice: 1050.85,
    ProductImage: M2,
    BrandName: 'Xiaomi',  
    value: 'L',
    category:"Fashion",
    subcategory: 'Shirt',
    img1: product3,
    img2: product2,
    img3: product3,
    img4: M2 
  },

  {
    id: 11,
    ProductName: 'Fashion2', 
    Price: 999.0,
    OldPrice: 1050.85,
    ProductImage: product2,
    BrandName: 'Xiaomi',  
    value: 'P',
    category:"Grocery",
    subcategory: 'Kitchen',
    img1: product3,
    img2: product2,
    img3: product3,
    img4: M2 
  },
  {
    id: 12,
    ProductName: 'Fashion3', 
    Price: 999.0,
    OldPrice: 1050.85,
    ProductImage: M2,
    BrandName: 'Xiaomi',  
    value: 'P',
    category:"Grocery",
    subcategory: 'Vegitable',
    img1: product3,
    img2: product2,
    img3: product3,
    img4: M2 
  },
  {
    id: 13,
    ProductName: 'Fashion4', 
    Price: 999.0,
    OldPrice: 1050.85,
    ProductImage: M2,
    BrandName: 'Xiaomi',  
    value: 'L',
    category:"Grocery",
    subcategory: 'Fruit',
    img1: product3,
    img2: product2,
    img3: product3,
    img4: M2 
  },
];
